import { useState, useEffect, useCallback, useMemo, useRef } from 'react'
import { ThemeProvider, CssBaseline, Box, Snackbar, Alert } from '@mui/material'
import { EventsOn } from '../wailsjs/runtime/runtime'
import { ListTools, GetTool, RunTool, ListEnvironments, ExportTools, ImportTools } from '../wailsjs/go/main/App'
// @ts-ignore — GetPlatform is generated by Wails on next `wails dev` run
import { GetPlatform } from '../wailsjs/go/main/App'
// @ts-ignore — ListDeletedTools is generated by Wails on next `wails dev` run
import { ListDeletedTools } from '../wailsjs/go/main/App'
import { createAppTheme } from './theme'
import type { AppThemeMode } from './theme'
import type { Tool, ToolSummary, RunResult, EnvironmentSummary, Platform } from './types/tool'
import type { TabState, AppTab, RightSidebarContent, ActiveFunction } from './types/tabs'
import { initialTabState, getActiveTab, getSlotActiveTab } from './types/tabs'
import { useResizable } from './hooks/useResizable'
import { useNavHistory, findTab } from './hooks/useNavHistory'
import TitleBar from './components/Layout/TitleBar'
import FunctionBar from './components/Layout/FunctionBar'
import SidePanel from './components/Layout/SidePanel'
import MainArea from './components/Layout/MainArea'
import RightSidebar from './components/Layout/RightSidebar'
import OutputPanel from './components/OutputPanel/OutputPanel'


export default function App() {
  // ── Theme ────────────────────────────────────────────────
  const [mode, setMode] = useState<AppThemeMode>(() => {
    const saved = localStorage.getItem('zeonta-theme') as AppThemeMode | null
    if (saved === 'light' || saved === 'dark') return saved
    return window.matchMedia('(prefers-color-scheme: light)').matches ? 'light' : 'dark'
  })
  const theme = useMemo(() => createAppTheme(mode), [mode])
  const toggleMode = useCallback(() => {
    setMode(prev => {
      const next = prev === 'dark' ? 'light' : 'dark'
      localStorage.setItem('zeonta-theme', next)
      return next
    })
  }, [])
  useEffect(() => {
    document.documentElement.setAttribute('data-theme', mode)
  }, [mode])

  // ── Platform ─────────────────────────────────────────────
  const [platform, setPlatform] = useState<Platform>('windows')
  useEffect(() => { GetPlatform().then((p: string) => setPlatform(p as Platform)) }, [])

  // ── Data ─────────────────────────────────────────────────
  const [tools, setTools] = useState<ToolSummary[]>([])
  const [activeEnvironment, setActiveEnvironment] = useState<EnvironmentSummary | null>(null)
  const [trashCount, setTrashCount] = useState(0)

  const refreshTools = useCallback(async () => {
    const list = await ListTools()
    setTools(list ?? [])
  }, [])

  const refreshActiveEnvironment = useCallback(async () => {
    const list = await ListEnvironments()
    setActiveEnvironment((list ?? []).find(e => e.isActive) ?? null)
  }, [])

  const refreshTrashCount = useCallback(async () => {
    try {
      const list = await ListDeletedTools()
      setTrashCount((list ?? []).length)
    } catch { /* bindings not ready yet */ }
  }, [])

  useEffect(() => {
    let retryTimer: ReturnType<typeof setTimeout>
    const init = async () => {
      try {
        await refreshTools()
        await refreshActiveEnvironment()
        await refreshTrashCount()
      } catch {
        retryTimer = setTimeout(init, 100)
      }
    }
    init()
    return () => clearTimeout(retryTimer)
  }, [refreshTools, refreshActiveEnvironment, refreshTrashCount])

  // ── Tool cache (replaces selectedTool state) ─────────────
  const [toolCache, setToolCache] = useState<Record<string, Tool>>({})

  const fetchToolIntoCache = useCallback(async (toolId: string) => {
    try {
      const tool = await GetTool(toolId)
      setToolCache(prev => ({ ...prev, [toolId]: tool }))
    } catch { /* ignore */ }
  }, [])

  // ── Tab system ───────────────────────────────────────────
  const [tabState, setTabState] = useState<TabState>(initialTabState)
  const [saveCount, setSaveCount] = useState(0)

  // ── Navigation history (Go Back / Go Forward) ────────────
  const { pushNav, goBack, goForward, canGoBack, canGoForward } = useNavHistory()
  // Tracks the last pushed "slotIndex:tabId" key to skip duplicates
  const prevNavKeyRef = useRef<string | null>(null)
  // Set true before programmatic back/forward to suppress the resulting push
  const skipNavPushRef = useRef(false)

  const openTab = useCallback((tab: AppTab) => {
    setTabState(prev => {
      const targetSlot = prev.activeSlot
      const slot = prev.slots[targetSlot]
      const existingIdx = slot.tabs.findIndex(t => t.id === tab.id)
      if (existingIdx !== -1) {
        // activate existing tab
        const newSlots = prev.slots.map((s, i) =>
          i === targetSlot ? { ...s, activeTabIndex: existingIdx } : s
        ) as TabState['slots']
        return { ...prev, slots: newSlots }
      }
      // add new tab
      const newTabs = [...slot.tabs, tab]
      const newSlots = prev.slots.map((s, i) =>
        i === targetSlot ? { ...s, tabs: newTabs, activeTabIndex: newTabs.length - 1 } : s
      ) as TabState['slots']
      return { ...prev, slots: newSlots }
    })
  }, [])

  const activateTab = useCallback((slotIndex: 0 | 1, tabIndex: number) => {
    setTabState(prev => {
      const newSlots = prev.slots.map((s, i) =>
        i === slotIndex ? { ...s, activeTabIndex: tabIndex } : s
      ) as TabState['slots']
      return { ...prev, slots: newSlots, activeSlot: slotIndex }
    })
    // close edit/versions sidebar when switching away from tool tabs
    setTabState(prev => {
      const tab = prev.slots[slotIndex].tabs[tabIndex]
      if (tab?.kind !== 'tool') {
        setRightSidebar(prev =>
          prev?.kind === 'versions' ? null : prev
        )
      }
      return prev
    })
  }, [])

  // Watch tabState for active-tab changes and push to nav history.
  // This covers openTab, activateTab, and all other paths.
  useEffect(() => {
    const slot = tabState.slots[tabState.activeSlot]
    const activeTab = slot.tabs[slot.activeTabIndex] ?? null
    if (!activeTab) return
    const key = `${tabState.activeSlot}:${activeTab.id}`
    if (key === prevNavKeyRef.current) return
    prevNavKeyRef.current = key
    if (!skipNavPushRef.current) {
      pushNav({ slotIndex: tabState.activeSlot, tab: activeTab })
    }
    skipNavPushRef.current = false
  }, [tabState, pushNav])

  const handleGoBack = useCallback(() => {
    const entry = goBack()
    if (!entry) return
    skipNavPushRef.current = true
    const location = findTab(tabState, entry)
    if (location) {
      activateTab(location.slotIndex, location.tabIndex)
    } else {
      openTab(entry.tab)
    }
  }, [tabState, goBack, activateTab, openTab])

  const handleGoForward = useCallback(() => {
    const entry = goForward()
    if (!entry) return
    skipNavPushRef.current = true
    const location = findTab(tabState, entry)
    if (location) {
      activateTab(location.slotIndex, location.tabIndex)
    } else {
      openTab(entry.tab)
    }
  }, [tabState, goForward, activateTab, openTab])

  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.altKey && e.key === 'ArrowLeft')  { e.preventDefault(); handleGoBack() }
      if (e.altKey && e.key === 'ArrowRight') { e.preventDefault(); handleGoForward() }
    }
    window.addEventListener('keydown', handler)
    return () => window.removeEventListener('keydown', handler)
  }, [handleGoBack, handleGoForward])

  const closeTab = useCallback((slotIndex: 0 | 1, tabIndex: number) => {
    setTabState(prev => {
      const slot = prev.slots[slotIndex]
      const newTabs = slot.tabs.filter((_, i) => i !== tabIndex)
      const newActiveIdx = Math.min(slot.activeTabIndex, Math.max(0, newTabs.length - 1))
      const newSlots = prev.slots.map((s, i) =>
        i === slotIndex ? { ...s, tabs: newTabs, activeTabIndex: newActiveIdx } : s
      ) as TabState['slots']
      // collapse split if slot 1 becomes empty
      const splitEnabled = slotIndex === 1 && newTabs.length === 0 ? false : prev.splitEnabled
      return { ...prev, slots: newSlots, splitEnabled }
    })
  }, [])

  const reorderTabs = useCallback((fromSlot: 0 | 1, fromIndex: number, toSlot: 0 | 1, toIndex: number) => {
    setTabState(prev => {
      if (fromSlot === toSlot) {
        // same-slot reorder
        const slot = prev.slots[fromSlot]
        const newTabs = [...slot.tabs]
        const [moved] = newTabs.splice(fromIndex, 1)
        newTabs.splice(toIndex, 0, moved)
        let activeIdx = slot.activeTabIndex
        if (activeIdx === fromIndex) {
          activeIdx = toIndex > fromIndex ? toIndex - 1 : toIndex
        } else if (fromIndex < toIndex && activeIdx > fromIndex && activeIdx <= toIndex) {
          activeIdx--
        } else if (fromIndex > toIndex && activeIdx < fromIndex && activeIdx >= toIndex) {
          activeIdx++
        }
        const newSlots = prev.slots.map((s, i) =>
          i === fromSlot ? { ...s, tabs: newTabs, activeTabIndex: activeIdx } : s
        ) as TabState['slots']
        return { ...prev, slots: newSlots }
      } else {
        // cross-slot move: remove from source, insert into destination
        const src = prev.slots[fromSlot]
        const dst = prev.slots[toSlot]
        const tab = src.tabs[fromIndex]
        const newSrcTabs = src.tabs.filter((_, i) => i !== fromIndex)
        const newSrcActiveIdx = Math.min(src.activeTabIndex, Math.max(0, newSrcTabs.length - 1))
        const insertAt = Math.min(toIndex, dst.tabs.length)
        const newDstTabs = [...dst.tabs]
        newDstTabs.splice(insertAt, 0, tab)
        const newSlots = prev.slots.map((s, i) => {
          if (i === fromSlot) return { ...s, tabs: newSrcTabs, activeTabIndex: newSrcActiveIdx }
          if (i === toSlot) return { ...s, tabs: newDstTabs, activeTabIndex: insertAt }
          return s
        }) as TabState['slots']
        // collapse split if source slot 1 becomes empty
        const splitEnabled = fromSlot === 1 && newSrcTabs.length === 0 ? false : prev.splitEnabled
        return { ...prev, slots: newSlots, splitEnabled, activeSlot: toSlot }
      }
    })
  }, [])

  const toggleSplit = useCallback(() => {
    setTabState(prev => {
      if (prev.splitEnabled) {
        // merge slot 1 tabs into slot 0
        const merged = [...prev.slots[0].tabs, ...prev.slots[1].tabs]
        const newSlots: TabState['slots'] = [
          { tabs: merged, activeTabIndex: prev.slots[0].activeTabIndex },
          { tabs: [], activeTabIndex: 0 },
        ]
        return { ...prev, slots: newSlots, splitEnabled: false, activeSlot: 0 }
      }
      return { ...prev, splitEnabled: true }
    })
  }, [])

  // derived: active tool from the active slot
  const selectedTool = useMemo(() => {
    const tab = getActiveTab(tabState)
    return tab?.kind === 'tool' && tab.toolId ? (toolCache[tab.toolId] ?? null) : null
  }, [tabState, toolCache])

  // active tool id for sidebar highlight — check both slots
  const selectedToolId = useMemo(() => {
    const slot0Tab = getSlotActiveTab(tabState.slots[0])
    const slot1Tab = getSlotActiveTab(tabState.slots[1])
    const activeTab = tabState.activeSlot === 0 ? slot0Tab : slot1Tab
    return activeTab?.kind === 'tool' ? activeTab.toolId ?? null : null
  }, [tabState])

  // ── Right sidebar ────────────────────────────────────────
  const [rightSidebar, setRightSidebar] = useState<RightSidebarContent>(null)
  const [envRefreshSignal, setEnvRefreshSignal] = useState(0)

  const handleNewTool = useCallback(() => {
    openTab({ id: 'new-tool', kind: 'new-tool', title: 'New Tool' })
  }, [openTab])

  const historyVersionCache = useRef<Record<string, { toolId: string; versionId: string }>>({})

  const handleViewVersion = useCallback((toolId: string, versionId: string) => {
    setRightSidebar({ kind: 'versions', toolId, initialVersionId: versionId })
  }, [])

  const handleHistoryVersionFound = useCallback((entryId: string, toolId: string, versionId: string) => {
    historyVersionCache.current[entryId] = { toolId, versionId }
  }, [])

  // Auto-sync right sidebar with the active tool tab
  useEffect(() => {
    const slot = tabState.slots[tabState.activeSlot]
    const activeTab = slot.tabs[slot.activeTabIndex] ?? null
    if (activeTab?.kind === 'tool' && activeTab.toolId) {
      setRightSidebar(prev =>
        prev?.kind === 'versions' && prev.toolId === activeTab.toolId && prev.initialVersionId === undefined ? prev
          : { kind: 'versions', toolId: activeTab.toolId! }
      )
    } else if (activeTab?.kind === 'history-detail' && activeTab.entryId) {
      const ver = historyVersionCache.current[activeTab.entryId]
      setRightSidebar(ver ? { kind: 'versions', toolId: ver.toolId, initialVersionId: ver.versionId } : null)
    } else {
      setRightSidebar(prev => prev?.kind === 'versions' ? null : prev)
    }
  }, [tabState])

  const handleToolSaved = useCallback(async (id: string) => {
    await refreshTools()
    await fetchToolIntoCache(id)
    setSaveCount(c => c + 1)
    // update tab title if it exists
    setTabState(prev => {
      const newSlots = prev.slots.map(slot => ({
        ...slot,
        tabs: slot.tabs.map(t => t.id === id && t.kind === 'tool'
          ? { ...t, title: tools.find(x => x.id === id)?.name ?? t.title }
          : t
        ),
      })) as TabState['slots']
      return { ...prev, slots: newSlots }
    })
    // close new-tool tab after saving
    setTabState(prev => {
      const newSlots = prev.slots.map(slot => {
        const newTabs = slot.tabs.filter(t => t.id !== 'new-tool')
        return { ...slot, tabs: newTabs, activeTabIndex: Math.min(slot.activeTabIndex, Math.max(0, newTabs.length - 1)) }
      }) as TabState['slots']
      return { ...prev, slots: newSlots }
    })
    // open tool tab if not already open
    const toolSummary = (await ListTools().catch(() => [])).find((t: ToolSummary) => t.id === id)
    if (toolSummary) {
      openTab({ id, kind: 'tool', title: toolSummary.name, toolId: id })
    }
  }, [refreshTools, fetchToolIntoCache, tools, openTab])

  const handleToolDeleted = useCallback(async (toolId?: string) => {
    await refreshTools()
    await refreshTrashCount()
    if (toolId) {
      setToolCache(prev => { const n = { ...prev }; delete n[toolId]; return n })
      // close the tool's tab in all slots
      setTabState(prev => {
        const newSlots = prev.slots.map(slot => {
          const newTabs = slot.tabs.filter(t => t.id !== toolId)
          return { ...slot, tabs: newTabs, activeTabIndex: Math.min(slot.activeTabIndex, Math.max(0, newTabs.length - 1)) }
        }) as TabState['slots']
        return { ...prev, slots: newSlots }
      })
    }
    setRightSidebar(null)
  }, [refreshTools, refreshTrashCount])

  // ── Select tool from sidebar ─────────────────────────────
  const handleSelectTool = useCallback(async (id: string) => {
    if (!toolCache[id]) await fetchToolIntoCache(id)
    const name = tools.find(t => t.id === id)?.name ?? 'Tool'
    openTab({ id, kind: 'tool', title: name, toolId: id })
  }, [toolCache, tools, fetchToolIntoCache, openTab])

  // ── Output panel ─────────────────────────────────────────
  const [outputPanelOpen, setOutputPanelOpen] = useState(false)
  const [outputLines, setOutputLines] = useState<string[]>([])
  const [runResult, setRunResult] = useState<RunResult | null>(null)
  const [runCount, setRunCount] = useState(0)
  const [isRunning, setIsRunning] = useState(false)

  useEffect(() => {
    let offOutput: (() => void) | undefined
    let offDone: (() => void) | undefined
    let retryTimer: ReturnType<typeof setTimeout>
    const register = () => {
      try {
        offOutput = EventsOn('tool:output', (line: string) => {
          setOutputLines(prev => [...prev, line])
        })
        offDone = EventsOn('tool:done', (result: RunResult) => {
          setRunResult(result)
          setRunCount(c => c + 1)
          setIsRunning(false)
        })
      } catch {
        retryTimer = setTimeout(register, 100)
      }
    }
    register()
    return () => { clearTimeout(retryTimer); offOutput?.(); offDone?.() }
  }, [])

  const handleRunStart = useCallback(() => {
    setOutputLines([])
    setRunResult(null)
    setIsRunning(true)
    setOutputPanelOpen(true)
  }, [])

  const handleRun = useCallback((toolId: string, paramValues: Record<string, string>) => {
    handleRunStart()
    RunTool({ toolId, paramValues })
  }, [handleRunStart])

  // ── Layout sizes ─────────────────────────────────────────
  const [activeFunction, setActiveFunction] = useState<ActiveFunction>('tools')
  const [leftPanelOpen, setLeftPanelOpen] = useState(() =>
    localStorage.getItem('zeonta-left-panel-open') !== 'false'
  )
  const [rightSidebarVisible, setRightSidebarVisible] = useState(true)
  const [sidebarWidth, setSidebarWidth] = useResizable('zeonta-sidebar-width', 240)
  const [rightSidebarWidth, setRightSidebarWidth] = useResizable('zeonta-right-sidebar-width', 400)
  const [outputPanelHeight, setOutputPanelHeight] = useResizable('zeonta-output-height', 220)
  const [splitRatio, setSplitRatio] = useResizable('zeonta-split-ratio', 50)

  const handleSelectFunction = useCallback((fn: ActiveFunction) => {
    if (fn === activeFunction && leftPanelOpen) {
      setLeftPanelOpen(false)
      localStorage.setItem('zeonta-left-panel-open', 'false')
    } else {
      setActiveFunction(fn)
      setLeftPanelOpen(true)
      localStorage.setItem('zeonta-left-panel-open', 'true')
    }
  }, [activeFunction, leftPanelOpen])

  const toggleLeftPanel = useCallback(() => {
    setLeftPanelOpen(prev => {
      const next = !prev
      localStorage.setItem('zeonta-left-panel-open', String(next))
      return next
    })
  }, [])

  const toggleRightSidebar = useCallback(() => {
    setRightSidebarVisible(prev => !prev)
  }, [])

  // track main area container width for split ratio calculation
  const mainAreaRef = useRef<HTMLDivElement>(null)
  const [mainAreaWidth, setMainAreaWidth] = useState(800)
  useEffect(() => {
    if (!mainAreaRef.current) return
    const ro = new ResizeObserver(entries => {
      setMainAreaWidth(entries[0].contentRect.width)
    })
    ro.observe(mainAreaRef.current)
    return () => ro.disconnect()
  }, [])

  // ── Import / Export ──────────────────────────────────────
  const [snackbar, setSnackbar] = useState<{ open: boolean; message: string; severity: 'success' | 'error' }>({
    open: false, message: '', severity: 'success',
  })
  const showSnackbar = useCallback((message: string, severity: 'success' | 'error') => {
    setSnackbar({ open: true, message, severity })
  }, [])

  const handleExport = useCallback(async (ids: string[]): Promise<boolean> => {
    try {
      const exported = await ExportTools(ids)
      if (exported) showSnackbar('Tools exported successfully', 'success')
      return exported
    } catch (e: any) {
      showSnackbar(`Export failed: ${e}`, 'error')
      return false
    }
  }, [showSnackbar])

  const handleImport = useCallback(async () => {
    try {
      const result = await ImportTools()
      if (result.imported === 0 && result.skipped.length === 0) return
      const skippedPart = result.skipped.length > 0 ? ` · Skipped: ${result.skipped.join(', ')}` : ''
      showSnackbar(`Imported ${result.imported} tool${result.imported !== 1 ? 's' : ''}${skippedPart}`, 'success')
      await refreshTools()
    } catch (e: any) {
      showSnackbar(`Import failed: ${e}`, 'error')
    }
  }, [refreshTools, showSnackbar])

  const handleRestored = useCallback(async (toolId: string) => {
    await refreshTools()
    await refreshTrashCount()
    await fetchToolIntoCache(toolId)
  }, [refreshTools, refreshTrashCount, fetchToolIntoCache])

  const handleTrashCleared = useCallback(async () => {
    await refreshTrashCount()
  }, [refreshTrashCount])

  // ── Render ───────────────────────────────────────────────
  return (
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <Box className="flex flex-col h-screen overflow-hidden" sx={{ bgcolor: 'background.default' }}>

        <TitleBar
          leftPanelOpen={leftPanelOpen}
          onToggleLeftPanel={toggleLeftPanel}
          bottomPanelOpen={outputPanelOpen}
          onToggleBottomPanel={() => setOutputPanelOpen(prev => !prev)}
          rightSidebarVisible={rightSidebarVisible}
          onToggleRightSidebar={toggleRightSidebar}
          canGoBack={canGoBack}
          canGoForward={canGoForward}
          onGoBack={handleGoBack}
          onGoForward={handleGoForward}
        />

        <Box className="flex flex-1 overflow-hidden">

          <FunctionBar
            activeFunction={activeFunction}
            leftPanelOpen={leftPanelOpen}
            onSelectFunction={handleSelectFunction}
            trashCount={trashCount}
            activeEnvironment={activeEnvironment}
            themeMode={mode}
            onToggleTheme={toggleMode}
          />

          <SidePanel
            activeFunction={activeFunction}
            open={leftPanelOpen}
            width={sidebarWidth}
            onResizeWidth={setSidebarWidth}
            tools={tools}
            selectedToolId={selectedToolId}
            onSelectTool={handleSelectTool}
            onNewTool={handleNewTool}
            onImport={handleImport}
            runCount={runCount}
            onSelectHistoryEntry={(id, toolName) => openTab({
              id: `history-detail-${id}`,
              kind: 'history-detail',
              title: toolName,
              entryId: id,
            })}
            trashCount={trashCount}
            onRestored={handleRestored}
            onTrashCleared={handleTrashCleared}
            onSelectTrashTool={(toolId, toolName) => openTab({
              id: `trash-detail-${toolId}`,
              kind: 'trash-detail',
              title: toolName,
              toolId,
            })}
            onExport={handleExport}
            envRefreshSignal={envRefreshSignal}
            onNewEnvironment={() => openTab({
              id: 'env-edit-new',
              kind: 'environment-edit',
              title: 'New Environment',
            })}
            onEditEnvironment={(id) => openTab({
              id: `env-edit-${id}`,
              kind: 'environment-edit',
              title: 'Edit Environment',
              environmentId: id,
            })}
            onActiveEnvironmentChanged={refreshActiveEnvironment}
          />

          <Box ref={mainAreaRef} className="flex flex-col flex-1 overflow-hidden">
            <MainArea
              tabState={tabState}
              splitRatio={splitRatio}
              onSplitResize={setSplitRatio}
              onActivateTab={activateTab}
              onCloseTab={closeTab}
              onReorderTabs={reorderTabs}
              onToggleSplit={toggleSplit}
              onSlotClick={(slotIndex) => setTabState(prev => ({ ...prev, activeSlot: slotIndex }))}
              containerWidth={mainAreaWidth}
              toolCache={toolCache}
              tools={tools}
              runCount={runCount}
              activeEnvironment={activeEnvironment}
              onSaved={handleToolSaved}
              onRun={handleRun}
              onToolDeleted={() => handleToolDeleted(selectedToolId ?? undefined)}
              onViewVersion={handleViewVersion}
              onRestored={handleRestored}
              onEnvironmentSaved={() => { refreshActiveEnvironment(); setEnvRefreshSignal(c => c + 1) }}
              onHistoryVersionFound={handleHistoryVersionFound}
              platform={platform}
            />

            {outputPanelOpen && (
              <OutputPanel
                tool={selectedTool}
                lines={outputLines}
                result={runResult}
                running={isRunning}
                height={outputPanelHeight}
                onResize={setOutputPanelHeight}
                onClose={() => { setOutputPanelOpen(false); setOutputLines([]); setRunResult(null); setIsRunning(false) }}
              />
            )}
          </Box>

          {rightSidebarVisible && (
            <RightSidebar
              content={rightSidebar}
              width={rightSidebarWidth}
              onResize={setRightSidebarWidth}
              tool={selectedTool}
              saveCount={saveCount}
              onRestored={(id) => handleRestored(id)}
              onRunStart={handleRunStart}
              onViewVersion={handleViewVersion}
              onClose={() => setRightSidebar(null)}
            />
          )}

        </Box>

      </Box>

      <Snackbar
        open={snackbar.open}
        autoHideDuration={4000}
        onClose={() => setSnackbar(s => ({ ...s, open: false }))}
        anchorOrigin={{ vertical: 'bottom', horizontal: 'center' }}
      >
        <Alert severity={snackbar.severity} onClose={() => setSnackbar(s => ({ ...s, open: false }))} sx={{ width: '100%' }}>
          {snackbar.message}
        </Alert>
      </Snackbar>
    </ThemeProvider>
  )
}
