import { useState, useEffect, useCallback, useMemo, useRef } from 'react'
import { ThemeProvider, CssBaseline, Box, Snackbar, Alert } from '@mui/material'
import { EventsOn } from '../wailsjs/runtime/runtime'
import { ListTools, GetTool, RunTool, ListEnvironments, ExportTools, ImportTools } from '../wailsjs/go/main/App'
// @ts-ignore — ListDeletedTools is generated by Wails on next `wails dev` run
import { ListDeletedTools } from '../wailsjs/go/main/App'
import { createAppTheme } from './theme'
import type { AppThemeMode } from './theme'
import type { Tool, ToolSummary, RunResult, EnvironmentSummary } from './types/tool'
import type { TabState, AppTab, RightSidebarContent } from './types/tabs'
import { initialTabState, getActiveTab, getSlotActiveTab } from './types/tabs'
import { useResizable } from './hooks/useResizable'
import Sidebar from './components/Sidebar/Sidebar'
import MainArea from './components/Layout/MainArea'
import RightSidebar from './components/Layout/RightSidebar'
import OutputPanel from './components/OutputPanel/OutputPanel'

export type EditPanelMode = 'create' | 'edit' | null

export default function App() {
  // ── Theme ────────────────────────────────────────────────
  const [mode, setMode] = useState<AppThemeMode>(() => {
    const saved = localStorage.getItem('zeonta-theme') as AppThemeMode | null
    if (saved === 'light' || saved === 'dark') return saved
    return window.matchMedia('(prefers-color-scheme: light)').matches ? 'light' : 'dark'
  })
  const theme = useMemo(() => createAppTheme(mode), [mode])
  const toggleMode = useCallback(() => {
    setMode(prev => {
      const next = prev === 'dark' ? 'light' : 'dark'
      localStorage.setItem('zeonta-theme', next)
      return next
    })
  }, [])
  useEffect(() => {
    document.documentElement.setAttribute('data-theme', mode)
  }, [mode])

  // ── Data ─────────────────────────────────────────────────
  const [tools, setTools] = useState<ToolSummary[]>([])
  const [activeEnvironment, setActiveEnvironment] = useState<EnvironmentSummary | null>(null)
  const [trashCount, setTrashCount] = useState(0)

  const refreshTools = useCallback(async () => {
    const list = await ListTools()
    setTools(list ?? [])
  }, [])

  const refreshActiveEnvironment = useCallback(async () => {
    const list = await ListEnvironments()
    setActiveEnvironment((list ?? []).find(e => e.isActive) ?? null)
  }, [])

  const refreshTrashCount = useCallback(async () => {
    try {
      const list = await ListDeletedTools()
      setTrashCount((list ?? []).length)
    } catch { /* bindings not ready yet */ }
  }, [])

  useEffect(() => {
    let retryTimer: ReturnType<typeof setTimeout>
    const init = async () => {
      try {
        await refreshTools()
        await refreshActiveEnvironment()
        await refreshTrashCount()
      } catch {
        retryTimer = setTimeout(init, 100)
      }
    }
    init()
    return () => clearTimeout(retryTimer)
  }, [refreshTools, refreshActiveEnvironment, refreshTrashCount])

  // ── Tool cache (replaces selectedTool state) ─────────────
  const [toolCache, setToolCache] = useState<Record<string, Tool>>({})

  const fetchToolIntoCache = useCallback(async (toolId: string) => {
    try {
      const tool = await GetTool(toolId)
      setToolCache(prev => ({ ...prev, [toolId]: tool }))
    } catch { /* ignore */ }
  }, [])

  // ── Tab system ───────────────────────────────────────────
  const [tabState, setTabState] = useState<TabState>(initialTabState)
  const [saveCount, setSaveCount] = useState(0)

  const openTab = useCallback((tab: AppTab) => {
    setTabState(prev => {
      const targetSlot = prev.activeSlot
      const slot = prev.slots[targetSlot]
      const existingIdx = slot.tabs.findIndex(t => t.id === tab.id)
      if (existingIdx !== -1) {
        // activate existing tab
        const newSlots = prev.slots.map((s, i) =>
          i === targetSlot ? { ...s, activeTabIndex: existingIdx } : s
        ) as TabState['slots']
        return { ...prev, slots: newSlots }
      }
      // add new tab
      const newTabs = [...slot.tabs, tab]
      const newSlots = prev.slots.map((s, i) =>
        i === targetSlot ? { ...s, tabs: newTabs, activeTabIndex: newTabs.length - 1 } : s
      ) as TabState['slots']
      return { ...prev, slots: newSlots }
    })
  }, [])

  const activateTab = useCallback((slotIndex: 0 | 1, tabIndex: number) => {
    setTabState(prev => {
      const newSlots = prev.slots.map((s, i) =>
        i === slotIndex ? { ...s, activeTabIndex: tabIndex } : s
      ) as TabState['slots']
      return { ...prev, slots: newSlots, activeSlot: slotIndex }
    })
    // auto-close right sidebar if new active tab is not a tool tab
    setTabState(prev => {
      const tab = prev.slots[slotIndex].tabs[tabIndex]
      if (tab?.kind !== 'tool') setRightSidebar(null)
      return prev
    })
  }, [])

  const closeTab = useCallback((slotIndex: 0 | 1, tabIndex: number) => {
    setTabState(prev => {
      const slot = prev.slots[slotIndex]
      const newTabs = slot.tabs.filter((_, i) => i !== tabIndex)
      const newActiveIdx = Math.min(slot.activeTabIndex, Math.max(0, newTabs.length - 1))
      const newSlots = prev.slots.map((s, i) =>
        i === slotIndex ? { ...s, tabs: newTabs, activeTabIndex: newActiveIdx } : s
      ) as TabState['slots']
      // collapse split if slot 1 becomes empty
      const splitEnabled = slotIndex === 1 && newTabs.length === 0 ? false : prev.splitEnabled
      return { ...prev, slots: newSlots, splitEnabled }
    })
  }, [])

  const toggleSplit = useCallback(() => {
    setTabState(prev => {
      if (prev.splitEnabled) {
        // merge slot 1 tabs into slot 0
        const merged = [...prev.slots[0].tabs, ...prev.slots[1].tabs]
        const newSlots: TabState['slots'] = [
          { tabs: merged, activeTabIndex: prev.slots[0].activeTabIndex },
          { tabs: [], activeTabIndex: 0 },
        ]
        return { ...prev, slots: newSlots, splitEnabled: false, activeSlot: 0 }
      }
      return { ...prev, splitEnabled: true }
    })
  }, [])

  // derived: active tool from the active slot
  const selectedTool = useMemo(() => {
    const tab = getActiveTab(tabState)
    return tab?.kind === 'tool' && tab.toolId ? (toolCache[tab.toolId] ?? null) : null
  }, [tabState, toolCache])

  // active tool id for sidebar highlight — check both slots
  const selectedToolId = useMemo(() => {
    const slot0Tab = getSlotActiveTab(tabState.slots[0])
    const slot1Tab = getSlotActiveTab(tabState.slots[1])
    const activeTab = tabState.activeSlot === 0 ? slot0Tab : slot1Tab
    return activeTab?.kind === 'tool' ? activeTab.toolId ?? null : null
  }, [tabState])

  // ── Right sidebar ────────────────────────────────────────
  const [rightSidebar, setRightSidebar] = useState<RightSidebarContent>(null)

  const handleEdit = useCallback(() => {
    setRightSidebar({ kind: 'edit', mode: 'edit' })
  }, [])

  const handleNewTool = useCallback(() => {
    setRightSidebar({ kind: 'edit', mode: 'create' })
  }, [])

  const handleVersions = useCallback((toolId: string) => {
    setRightSidebar({ kind: 'versions', toolId })
  }, [])

  const handleViewVersion = useCallback((toolId: string, versionId: string) => {
    setRightSidebar({ kind: 'versions', toolId, initialVersionId: versionId })
  }, [])

  const handleToolSaved = useCallback(async (id: string) => {
    await refreshTools()
    await fetchToolIntoCache(id)
    setSaveCount(c => c + 1)
    // update tab title if it exists
    setTabState(prev => {
      const newSlots = prev.slots.map(slot => ({
        ...slot,
        tabs: slot.tabs.map(t => t.id === id && t.kind === 'tool'
          ? { ...t, title: tools.find(x => x.id === id)?.name ?? t.title }
          : t
        ),
      })) as TabState['slots']
      return { ...prev, slots: newSlots }
    })
    // if creating new tool, switch edit mode to 'edit'
    setRightSidebar(prev => prev?.kind === 'edit' && prev.mode === 'create'
      ? { kind: 'edit', mode: 'edit' }
      : prev
    )
    // open tool tab if not already open
    const toolSummary = (await ListTools().catch(() => [])).find((t: ToolSummary) => t.id === id)
    if (toolSummary) {
      openTab({ id, kind: 'tool', title: toolSummary.name, toolId: id })
    }
  }, [refreshTools, fetchToolIntoCache, tools, openTab])

  const handleToolDeleted = useCallback(async (toolId?: string) => {
    await refreshTools()
    await refreshTrashCount()
    if (toolId) {
      setToolCache(prev => { const n = { ...prev }; delete n[toolId]; return n })
      // close the tool's tab in all slots
      setTabState(prev => {
        const newSlots = prev.slots.map(slot => {
          const newTabs = slot.tabs.filter(t => t.id !== toolId)
          return { ...slot, tabs: newTabs, activeTabIndex: Math.min(slot.activeTabIndex, Math.max(0, newTabs.length - 1)) }
        }) as TabState['slots']
        return { ...prev, slots: newSlots }
      })
    }
    setRightSidebar(null)
  }, [refreshTools, refreshTrashCount])

  // ── Select tool from sidebar ─────────────────────────────
  const handleSelectTool = useCallback(async (id: string) => {
    if (!toolCache[id]) await fetchToolIntoCache(id)
    const name = tools.find(t => t.id === id)?.name ?? 'Tool'
    openTab({ id, kind: 'tool', title: name, toolId: id })
  }, [toolCache, tools, fetchToolIntoCache, openTab])

  // ── Output panel ─────────────────────────────────────────
  const [outputPanelOpen, setOutputPanelOpen] = useState(false)
  const [outputLines, setOutputLines] = useState<string[]>([])
  const [runResult, setRunResult] = useState<RunResult | null>(null)
  const [runCount, setRunCount] = useState(0)

  useEffect(() => {
    let offOutput: (() => void) | undefined
    let offDone: (() => void) | undefined
    let retryTimer: ReturnType<typeof setTimeout>
    const register = () => {
      try {
        offOutput = EventsOn('tool:output', (line: string) => {
          setOutputLines(prev => [...prev, line])
        })
        offDone = EventsOn('tool:done', (result: RunResult) => {
          setRunResult(result)
          setRunCount(c => c + 1)
        })
      } catch {
        retryTimer = setTimeout(register, 100)
      }
    }
    register()
    return () => { clearTimeout(retryTimer); offOutput?.(); offDone?.() }
  }, [])

  const handleRunStart = useCallback(() => {
    setOutputLines([])
    setRunResult(null)
    setOutputPanelOpen(true)
  }, [])

  const handleRun = useCallback((toolId: string, paramValues: Record<string, string>) => {
    handleRunStart()
    RunTool({ toolId, paramValues })
  }, [handleRunStart])

  // ── Layout sizes ─────────────────────────────────────────
  const [sidebarCollapsed, setSidebarCollapsed] = useState(() =>
    localStorage.getItem('zeonta-sidebar-collapsed') === 'true'
  )
  const [sidebarWidth, setSidebarWidth] = useResizable('zeonta-sidebar-width', 240)
  const [rightSidebarWidth, setRightSidebarWidth] = useResizable('zeonta-right-sidebar-width', 500)
  const [outputPanelHeight, setOutputPanelHeight] = useResizable('zeonta-output-height', 220)
  const [splitRatio, setSplitRatio] = useResizable('zeonta-split-ratio', 50)

  const toggleSidebarCollapsed = useCallback(() => {
    setSidebarCollapsed(prev => {
      const next = !prev
      localStorage.setItem('zeonta-sidebar-collapsed', String(next))
      return next
    })
  }, [])

  // track main area container width for split ratio calculation
  const mainAreaRef = useRef<HTMLDivElement>(null)
  const [mainAreaWidth, setMainAreaWidth] = useState(800)
  useEffect(() => {
    if (!mainAreaRef.current) return
    const ro = new ResizeObserver(entries => {
      setMainAreaWidth(entries[0].contentRect.width)
    })
    ro.observe(mainAreaRef.current)
    return () => ro.disconnect()
  }, [])

  // ── Import / Export ──────────────────────────────────────
  const [snackbar, setSnackbar] = useState<{ open: boolean; message: string; severity: 'success' | 'error' }>({
    open: false, message: '', severity: 'success',
  })
  const showSnackbar = useCallback((message: string, severity: 'success' | 'error') => {
    setSnackbar({ open: true, message, severity })
  }, [])

  const handleExport = useCallback(async (ids: string[]): Promise<boolean> => {
    try {
      const exported = await ExportTools(ids)
      if (exported) showSnackbar('Tools exported successfully', 'success')
      return exported
    } catch (e: any) {
      showSnackbar(`Export failed: ${e}`, 'error')
      return false
    }
  }, [showSnackbar])

  const handleImport = useCallback(async () => {
    try {
      const result = await ImportTools()
      if (result.imported === 0 && result.skipped.length === 0) return
      const skippedPart = result.skipped.length > 0 ? ` · Skipped: ${result.skipped.join(', ')}` : ''
      showSnackbar(`Imported ${result.imported} tool${result.imported !== 1 ? 's' : ''}${skippedPart}`, 'success')
      await refreshTools()
    } catch (e: any) {
      showSnackbar(`Import failed: ${e}`, 'error')
    }
  }, [refreshTools, showSnackbar])

  const handleRestored = useCallback(async (toolId: string) => {
    await refreshTools()
    await refreshTrashCount()
    await fetchToolIntoCache(toolId)
  }, [refreshTools, refreshTrashCount, fetchToolIntoCache])

  const handleTrashCleared = useCallback(async () => {
    await refreshTrashCount()
  }, [refreshTrashCount])

  // ── Render ───────────────────────────────────────────────
  return (
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <Box className="flex h-screen overflow-hidden" sx={{ bgcolor: 'background.default' }}>

        <Sidebar
          tools={tools}
          selectedToolId={selectedToolId}
          activeEnvironment={activeEnvironment}
          onSelectTool={handleSelectTool}
          onNewTool={handleNewTool}
          onManageEnvironments={() => openTab({ id: 'environment', kind: 'environment', title: 'Environments' })}
          onExport={() => openTab({ id: 'export', kind: 'export', title: 'Export' })}
          onImport={handleImport}
          onHistory={() => openTab({ id: 'history', kind: 'history', title: 'History' })}
          onTrash={() => openTab({ id: 'trash', kind: 'trash', title: 'Trash' })}
          trashCount={trashCount}
          themeMode={mode}
          onToggleTheme={toggleMode}
          collapsed={sidebarCollapsed}
          onToggleCollapsed={toggleSidebarCollapsed}
          width={sidebarWidth}
          onResizeWidth={setSidebarWidth}
        />

        <Box ref={mainAreaRef} className="flex flex-col flex-1 overflow-hidden">
          <MainArea
            tabState={tabState}
            splitRatio={splitRatio}
            onSplitResize={setSplitRatio}
            onActivateTab={activateTab}
            onCloseTab={closeTab}
            onToggleSplit={toggleSplit}
            onSlotClick={(slotIndex) => setTabState(prev => ({ ...prev, activeSlot: slotIndex }))}
            containerWidth={mainAreaWidth}
            toolCache={toolCache}
            tools={tools}
            runCount={runCount}
            trashCount={trashCount}
            activeEnvironment={activeEnvironment}
            onEdit={handleEdit}
            onVersions={handleVersions}
            onRun={handleRun}
            onToolDeleted={() => handleToolDeleted(selectedToolId ?? undefined)}
            onViewVersion={handleViewVersion}
            onExport={handleExport}
            onActiveEnvironmentChanged={refreshActiveEnvironment}
            onImport={handleImport}
            onRestored={handleRestored}
            onTrashCleared={handleTrashCleared}
          />

          {outputPanelOpen && (
            <OutputPanel
              tool={selectedTool}
              lines={outputLines}
              result={runResult}
              height={outputPanelHeight}
              onResize={setOutputPanelHeight}
              onClose={() => setOutputPanelOpen(false)}
            />
          )}
        </Box>

        <RightSidebar
          content={rightSidebar}
          width={rightSidebarWidth}
          onResize={setRightSidebarWidth}
          tool={selectedTool}
          onSaved={handleToolSaved}
          saveCount={saveCount}
          onRestored={(id) => handleRestored(id)}
          onRunStart={handleRunStart}
          onClose={() => setRightSidebar(null)}
        />

      </Box>

      <Snackbar
        open={snackbar.open}
        autoHideDuration={4000}
        onClose={() => setSnackbar(s => ({ ...s, open: false }))}
        anchorOrigin={{ vertical: 'bottom', horizontal: 'center' }}
      >
        <Alert severity={snackbar.severity} onClose={() => setSnackbar(s => ({ ...s, open: false }))} sx={{ width: '100%' }}>
          {snackbar.message}
        </Alert>
      </Snackbar>
    </ThemeProvider>
  )
}
